config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/backend', as: 'rails_admin'
  devise_for :users
  # get '/', controller: 'pages', action: 'home' 以前專案寫法
  root 'candidates#index'    #等於get '/', to: 'candidates#index'
  get '/history', to: 'users#history'
  get '/orders', to: 'orders#index'
  resources :orders, only: [:index, :show, :new, :create]
  resources :products, only: [:index, :show]

  resource :cart, only: [:show, :destroy] do
    collection do
      put :add, path:'add/:id' 
      get :checkout
    end
  end
  
  resources :candidates do
    #member
    member do
      patch :vote
    end
  end
  
  namespace :admin do 
    root "pages#index"
    resources :candidates
  end
  
end

app/views/shared/_flash.html.erb
<%= flash_message(:alert) %>
<%= flash_message(:notice) %>

app/views/shared/_nav.html.erb
<nav class="top-nav">
<ul>
  <li><%= link_to "首頁", root_path%></li>
  <% if user_signed_in? %>
    <li>hi, <%= current_user.email%></li>
    <% unless current_cart.empty? %>
      <li>購物車<%= link_to "購物車(#{current_cart.items.count})",cart_path%></li>

      <li><%= current_cart.total_price %></li>
      <li><%= link_to "清空", cart_path, method: 'delete' %></li>
    <%end%>
    <li><%= link_to  "新增候選人",  new_candidate_path %></li>
    <li><%= link_to "我的投票紀錄", history_path if current_user.role == 'admin'%></li>
    <li><%=link_to "登出", destroy_user_session_path, method:'delete'%></li>
  <% else %>
  <li><%= link_to "登入", user_session_path %></li>
  <li><%= link_to "註冊", new_user_registration_path%></li>
  <% end %>
</ul>
</nav>