config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/backend', as: 'rails_admin'
  devise_for :users
  # get '/', controller: 'pages', action: 'home' 以前專案寫法
  root 'candidates#index'    #等於get '/', to: 'candidates#index'
  get '/history', to: 'users#history'
  get '/orders', to: 'orders#index'
  resources :orders, only: [:index, :show, :new, :create]
  resources :products, only: [:index, :show]

  resource :cart, only: [:show, :destroy] do
    collection do
      put :add, path:'add/:id' 
      get :checkout
    end
  end
  
  resources :candidates do
    #member
    member do
      patch :vote
    end
  end
  
  namespace :admin do 
    root "pages#index"
    resources :candidates
  end
  
end

app/models/candidate.rb
class Candidate < ApplicationRecord
    mount_uploader :avatar, AvatarUploader
    validates :name, presence: true
    validates :age, numericality: { greater_than_or_equal_to:40 }

    has_many :votes
    has_many :users, through: :votes
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController  
  before_action :find_candidate, only: [:show, :edit, :update, :destroy, :vote]
  before_action :authenticate_user!, except: [:index, :edit]
  def index
    @candidates = Candidate.all.page(params[:page]).per(3) #多人用複數
  end
  
  def show
    
  end
  
  def edit
    authorize @candidate
  end
  def update
    #還是要用id找
    if @candidate.update(candidate_params)
        redirect_to root_path, notice: '更新成功'
    else    
        render :edit
    end
  end
  def destroy
    authorize @candidate
    @candidate.destroy
    redirect_to root_path, notice: '資料已刪除'
  end
  def new
    @candidate = Candidate.new
    authorize @candidate
  end
  def create
    @candidate = Candidate.new(candidate_params)
    authorize @candidate

    if @candidate.save
        redirect_to root_path, notice: '新增成功'
    else    
        render :new
    end
  end

  def vote
    #已登入者的角度新增
    current_user.votes.create(ip_address: request.remote_ip, candidate: @candidate)
    # @candidate.increment(:vote)
    # @candidate.vote = @candidate.vote + 1
    # @candidate.save
    redirect_to root_path, notice: '投票完成'
  end
  private
  def candidate_params
    params.require(:candidate).permit(:name, :age, :party, :platform, :avatar)
  end
  def find_candidate
    @candidate = Candidate.find_by(id: params[:id])
  end
end

app/views/candidates/_form.html.erb
<% if candidate.errors.any? %>
<ul>
    <% candidate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
</ul>
<% end %>

<%= simple_form_for(candidate, html: { id: 'candidate_form' }) do |form| %> 
    <%= form.input  :name, label: '姓名'%>
    <%= form.input :age, label:'年齡' %>
    <%= form.input :party, label: '黨派' %>
    <%= form.input :platform, label: '政見' %>
    <%= form.input :avatar, label: '大頭照' %>
    <%= form.submit %>
<% end %>

app/views/candidates/create.html.erb
<h1>候選人列表</h1>
<a href= "/candidates/new">新增候選人</a>

app/views/candidates/edit.html.erb
<h1>更新候選人資料</h1>

<%= render 'form', candidate: @candidate %>

app/views/candidates/index.html.erb
<h1>候選人列表</h1>


<%= paginate @candidates, outer_window: 3 %>


<div class="candidates_wrap">

<% @candidates.each do |candidate| %>
    <div class="candidate">
        <div class="candidate_pic"> 
            <%= image_tag candidate.avatar_url(:small) if candidate.avatar? %>
            
        </div>
        <div class="candidate_info">
            <h2 class="vote"><%= candidate.vote %>票</h2>
            <h1><%= candidate.name%> (<%= candidate.age %>)</h1>
            <h2><%= candidate.party%></h2>
            <%= link_to "看政見", candidate, class:'more_detail'%>
            <%= link_to  "修改",  edit_candidate_path(candidate) if policy(candidate).edit?%> 
            <%= link_to  "投票",  vote_candidate_path(candidate), method:'patch', data: { confirm: '確認投票？'} if user_signed_in?%>
            <%= link_to  "刪除",  candidate, method: 'delete', data: { confirm: '確認刪除？'} if policy(candidate).destroy?%>
        </div>
    </div>
    
<% end %>


</div>

app/views/candidates/new.html.erb
<h1>新增候選人頁面</h1>


<%= render 'form', candidate: @candidate %>

app/views/candidates/show.html.erb
<h1><%= @candidate.name %></h1>
<ul>
  <li>年齡：<%= @candidate.age %></li>
  <li>黨派：<%= @candidate.party %></li>
  <li>政見：<%= simple_format(@candidate.platform) %></li>
</ul>

<%= link_to "回候選人列表", root_path %>

<ul>
  <% @candidate.users.each do |user|%>
    <li><%= user.email%></li>
  <% end %>
</ul>