config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/backend', as: 'rails_admin'
  devise_for :users
  # get '/', controller: 'pages', action: 'home' 以前專案寫法
  root 'candidates#index'    #等於get '/', to: 'candidates#index'
  get '/history', to: 'users#history'
  get '/orders', to: 'orders#index'
  resources :orders, only: [:index, :show, :new, :create]
  resources :products, only: [:index, :show]

  resource :cart, only: [:show, :destroy] do
    collection do
      put :add, path:'add/:id' 
      get :checkout
    end
  end
  
  resources :candidates do
    #member
    member do
      patch :vote
    end
  end
  
  namespace :admin do 
    root "pages#index"
    resources :candidates
  end
  
end

app/models/cart.rb
class Cart
    attr_reader :items
    def initialize(items = [])
        @items = items
    end
    #items會去找reader的items方法
    def add_item(product_id)
        found_item = items.find {|item| item.product_id == product_id}
        
        if found_item
            found_item.quantity += 1
        else
            items << CartItem.new(product_id)
        end
    end

    def empty?
        items.empty?
    end

    def total_price
        total = items.reduce(0){ |sum, item| sum + item.total_price}

        if xmas?
            total *= 0.9
        else
            total
        end
    end

    def serialize
        # result = [
        #     { product_id: 1, quantity: 3},
        #     { product_id: 2, quantity: 5}
        # ] 
        result = items.map { |item| 
            { "product_id"=> item.product_id, "quantity"=> item.quantity } 
        }
        return { "items" => result}
    end
    def self.from_hash(hash = nil)
        if hash && hash["items"] 
            #重組
            #組出充滿 CartItem 的陣列
            new hash["items"].map { |item| CartItem.new(item["product_id"], item["quantity"]) }
        else
            #新車
            new
        end
    end

    private 
    def xmas?
        Time.now.month == 12 && Time.now.day == 25
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    include CartHelper
    include Payable
    before_action :authenticate_user!

    def add
        current_cart.add_item(params[:id])
        session[:cart9527] = current_cart.serialize
        
        redirect_to products_path, notice: '已加入購物車'
    end
    
    def show
    end

    def checkout
        @order = Order.new
        @token = gateway.client_token.generate
        
    end
    def destroy
        session[:cart9527] = nil
        redirect_to products_path, notice: '購物車已清空'
    end
end

app/helpers/cart_helper.rb
module CartHelper
  def current_cart
    @ccaskj1929cc ||= Cart.from_hash(session[:cart9527])
  end

end

app/views/carts/_cart.html.erb
<table class="cart-table">
        <thead>
            <th>
                
                <td>商品名稱</td>
                <td>數量</td>
                <td>單價</td>
                <td>小計</td>
            </th>
        </thead>
        <tbody>
            <% current_cart.items.each do |item| %>
            <tr>
                <td></td>
                <td><%= item.product.title%></td>
                <td><%= item.quantity%></td>
                <td><%= item.product.price%></td>
                <td><%= item.total_price%></td>
            </tr>
            <% end %>
    
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3">總價</td>
                <td><%= current_cart.total_price%></td>
            </tr>
        </tfoot>
    </table>
    

app/views/carts/checkout.html.erb
<h1>結帳</h1>
<%= render  "cart" %>
<%= simple_form_for (@order) do |f| %>
    <%= f.input :recipient, label: false, placeholder: '請輸入收件人姓名'%>
    <%= f.input :phone, label: false, placeholder: '市話或行動電話'%>
    <%= f.input :address, label: false, placeholder: '收件人地址'%>
    <%= f.input :note, label: false, placeholder: '備註'%>
    <div id="payment-form"></div>    
    <%= f.submit '確認送出'%>
<% end %>

<script src="https://js.braintreegateway.com/js/braintree-2.32.1.min.js"></script>
<script>
        
        $(document).on("turbolinks:visit", function(){
            var clientToken = '<%=@token%>';
            braintree.setup(clientToken, "dropin", {
                container: "payment-form"
            });
        })
        
</script>

app/views/carts/show.html.erb
<h1>購物車</h1>

<%= render  "cart" %>
 <%= link_to  "繼續選購", products_path,class: 'btn btn-primary' %>
 <%= link_to  "結帳", checkout_cart_path,class: 'btn btn-danger' %>